library(tidyverse)
df <- read.csv("~/Documents/MATLAB/DataTable.csv")
colnames(df) <-c("id", "gene", "numRegions")
df1 <- read.csv("~/Documents/MATLAB/MERFISH_analysis/isoforms.fpkm_tracking_3col.txt", sep = "\t", header = T, stringsAsFactors=FALSE)
colnames(df1) <- c("id", "Gene", "FPKM")
df <- as.data.frame(sapply(df, function(x) gsub("\"", "", x)))
df2 <- merge(df,df1, by = "id", all = F)
df3 <- read.csv("~/Documents/MATLAB/MERFISH_analysis/Probe_list.txt")
df4 <- merge(df3, df2, by = "Gene", all = F)
df5 <- df4 %>% filter(FPKM < 100)
df6 <- df5 %>% filter(FPKM > 1)
